name: Release
on: workflow_dispatch

jobs:
  release:
    permissions:
      contents: write
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          skip-git-pull: "true"
          pre-commit: build/pre-commit.js
          release-count: 0
          version-file: "package.json, package-lock.json"
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
      - name: Read package.json node and npm engines version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: skjnldsv/read-package-engines-version-actions@v1.1
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^8'
      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}
      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"
      - name: Install Krankerl
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl_0.13.0_amd64.deb
          sudo dpkg -i krankerl_0.13.0_amd64.deb
      - name: Set up php
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package app
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: krankerl package
      - name: Attach tarball to github release
        uses: svenstaro/upload-release-action@v2
        id: attach_to_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/twofactor_admin.tar.gz
          asset_name: twofactor_admin-${{ steps.changelog.outputs.tag }}.tar.gz
          tag: ${{ steps.changelog.outputs.tag }}
          overwrite: true
      - name: Upload app to Nextcloud appstore
        uses: nextcloud-releases/nextcloud-appstore-push-action@v1
        with:
          app_name: ${{ env.twofactor_admin }}
          appstore_token: ${{ secrets.APPSTORE_TOKEN }}
          download_url: ${{ steps.attach_to_release.outputs.browser_download_url }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
